/const __sys_table / p
/const __conin / p
/const __conout / p
/const __cls / p
/const __puts / p
/const __getch / p
/const __locate / p
/const __cursor / p
/const __runtime_service / p
/const __boot_service / p
/const __set_wdt / p
/const __locate_protocol / p
/const __file_sys / p
/const __vol_open / p
/const __allocate_pages / p
/const __free_pages / p
/const __allocate_pool / p
/const __free_pool / p
/const __create_event / p
/const __set_timer / p
/const __wait_event / p
d
